### ISSUE TITLE
Will this be resolved? 

### ISSUE THREAD

**Issue by lesliewubbel** [maxcountryman/flask-uploads#54]
Traceback (most recent call last):
  File "e:\vessel_app\vessel_env\lib\site-packages\flask\cli.py", line 256, in locate_app
    __import__(module_name)
  File "E:\vessel_app\Vessel-app\Back-end\wsgi.py", line 1, in <module>
    from vessel_app import create_app
  File "E:\vessel_app\Vessel-app\Back-end\vessel_app\__init__.py", line 12, in <module>
    from flask_uploads import UploadSet, configure_uploads, IMAGES, patch_request_class
  File "e:\vessel_app\vessel_env\lib\site-packages\flask_uploads.py", line 26, in <module>
    from werkzeug import secure_filename, FileStorage
ImportError: cannot import name 'secure_filename' from 'werkzeug' (e:\vessel_app\vessel_env\lib\site-packages\werkzeug\__init__.py)

https://stackoverflow.com/questions/61628503/flask-uploads-importerror-cannot-import-name-secure-filename

**Comment by vavalomi** [comment]
it seems like the code itself was fixed a while ago, but new version never uploaded to pypi. You can install the latest version directly from here to circumvent the problem for now:
```pip install git+ssh://git@github.com/maxcountryman/flask-uploads```
or if you use https:
```pip install git+https://github.com/maxcountryman/flask-uploads```

**Comment by azmeuk** [comment]
This is indeed fixed by #28
