### ISSUE TITLE
Pypi package seems broken on Python 3.9

### ISSUE THREAD

**Issue by emmanuelito** [maxcountryman/flask-uploads#56]
`
$ pip install flask-upload

Collecting flask-upload
  Downloading Flask-Upload-0.0.1.zip (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: .../venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hq1ysap4/flask-upload_811c59d1191c4976a8cb3ac2017a1131/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hq1ysap4/flask-upload_811c59d1191c4976a8cb3ac2017a1131/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-k6iw5_li
         cwd: /tmp/pip-install-hq1ysap4/flask-upload_811c59d1191c4976a8cb3ac2017a1131/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hq1ysap4/flask-upload_811c59d1191c4976a8cb3ac2017a1131/setup.py", line 56, in <module>
        version=read_version('flask_upload/__init__.py'),
      File "/tmp/pip-install-hq1ysap4/flask-upload_811c59d1191c4976a8cb3ac2017a1131/setup.py", line 49, in read_version
        result = re.search(r'^__version__\s*=\s*[\'"]([^\'"]*)[\'"]',
      File "/usr/lib/python3.9/re.py", line 201, in search
        return _compile(pattern, flags).search(string)
    TypeError: cannot use a string pattern on a bytes-like object
    ----------------------------------------
`

**Comment by Skylor-Tang** [comment]
The module name is wrong, it should be `flask-uploads`
